# Standalone reference
version: '3'
services:
    mysql:
        networks:
            - web
        ports:
            - '3306:3306'
        container_name: mysql-5.7
        restart: always
        volumes:
            - './data:/var/lib/mysql'
            - "./config/conf.d:/etc/mysql/conf.d"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        image: 'mysql:5.7'
        labels:
            - "traefik.enable=false"
        deploy:
            resources:
                limits:
                    cpus: '3.5'
                    memory: 4096M
networks:
  web:
    external: true
