# standalone reference
version: '3'
services:
    phpmyadmin:
        networks:
            - web
        ports:
            - '9900:80'
        container_name: phpmyadmin-4.7
        restart: always
        environment:
            - PMA_ARBITRARY=1
        volumes:
            - '/opt/docker/phpmyadmin-4.7/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php'
        image: 'phpmyadmin/phpmyadmin:4.7'
        external_links:
          - mysql:mysql-5.7
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 512M
networks:
  web:
    external: true
